DEBUG: 2023-08-14 14:14:23,894: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:14:23,896: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 14:15:05,757: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:15:05,760: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 14:16:47,277: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:16:47,279: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 14:21:48,551: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:21:48,557: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 14:23:09,222: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:23:09,225: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 14:33:43,899: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:33:43,901: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 14:38:24,246: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 14:38:24,262: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 15:27:41,448: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 15:27:41,469: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 16:08:50,741: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 16:08:50,744: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 19:31:18,637: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 19:31:18,728: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 19:32:33,145: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 19:32:33,151: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 19:33:35,292: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 19:33:35,295: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 19:35:33,817: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 19:35:33,823: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
DEBUG: 2023-08-14 20:11:36,549: bcrypt.py: safe_verify: bcrypt: trapped unexpected response from 'os_crypt' backend: verify('test', b'$2$04$5BJqKfqMQvV7nS.yUguNcuRfMMOXK0xPWavM7pOzjEi5ze5T1k8/S'):
Traceback (most recent call last):
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 303, in safe_verify
    return verify(secret, hash)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/utils/handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/darix/Documents/fastapi-postgres/env/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 837, in _calc_checksum
    raise uh.exc.InternalBackendError(
passlib.exc.InternalBackendError: crypt.crypt() failed for unknown reason; passlib recommends running `pip install bcrypt` for general bcrypt support.(config=<hash <class 'str'> value omitted>, secret=<hash <class 'bytes'> value omitted>)
DEBUG: 2023-08-14 20:11:36,568: bcrypt.py: _finalize_backend_mixin: bcrypt: 'os_crypt' backend lacks $2$ support, enabling workaround
